src/main/java/org/springframework/dwarf/game/GameRepository.java, src/main/java/org/springframework/dwarf/game/GameService.java, src/main/java/org/springframework/dwarf/game/GameState.java, src/main/java/org/springframework/dwarf/worker/Worker.java, src/test/java/org/springframework/dwarf/game/GameRepositoryTest.java, src/test/java/org/springframework/dwarf/game/GameServiceTest.java
X is One,Two or Three. Returns the Player from a game by its Id.
=> Added searchPlayerXByGameId

src/main/java/org/springframework/dwarf/configuration/SecurityConfiguration.java, src/main/java/org/springframework/dwarf/game/Game.java, src/main/java/org/springframework/dwarf/game/GameState.java
Updated game and gamestate, made it so that not logged users cant access matches
=> State patterns update

src/main/java/org/springframework/dwarf/game/GameState.java
Added the first part of phaseResolution. Waiting for the pattern Strategy to complete it
=> Started phaseResolution() for ActionResolution

.github/workflows/build.yml, src/main/java/org/springframework/dwarf/player/PlayerController.java, src/main/java/org/springframework/dwarf/player/PlayerService.java, src/main/java/org/springframework/dwarf/strategies/CardStrategy.java, src/main/java/org/springframework/dwarf/user/User.java, src/main/java/org/springframework/dwarf/user/UserController.java, src/main/resources/db/hsqldb/data.sql
Co-Authored-By: José Ignacio <80249164+josgarboh@users.noreply.github.com>
=> Initial fix for Exceptions

src/main/java/org/springframework/dwarf/game/GameService.java, src/main/java/org/springframework/dwarf/game/GameState.java, src/test/java/org/springframework/dwarf/game/GameServiceTest.java
Optimized the code of phaseResolution() and created/tested the method searchPlayersByGame()
=> Simplifying code of phaseResolution() and created searchPlayersByGame

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/strategies/CardStrategy.java, src/main/resources/application.properties, src/main/webapp/WEB-INF/jsp/players/createOrUpdatePlayerForm.jsp, src/test/java/org/springframework/dwarf/player/PlayerControllerTests.java
Co-Authored-By: Pablo Álvarez <80222536+Pabalvcar@users.noreply.github.com>
=> Added logger to Strategy

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/player/PlayerService.java, src/main/java/org/springframework/dwarf/resources/Resources.java, src/main/java/org/springframework/dwarf/resources/ResourcesService.java, src/main/java/org/springframework/dwarf/worker/Worker.java, src/main/java/org/springframework/dwarf/worker/WorkerService.java, src/main/webapp/WEB-INF/jsp/board/board.jsp, src/main/webapp/WEB-INF/tags/playerInfo.tag
Workers and resources now create for each player in a game, resources show up in the board screen now
=> Workers and Resources created in boardInit

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/worker/Worker.java, src/main/webapp/WEB-INF/jsp/board/board.jsp
=> Added form ingame to place workers

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/game/GameController.java, src/main/java/org/springframework/dwarf/game/GameState.java, src/main/java/org/springframework/dwarf/player/PlayerController.java, src/main/java/org/springframework/dwarf/web/LoggedUserController.java, src/test/java/org/springframework/dwarf/player/PlayerControllerTests.java, src/test/java/org/springframework/dwarf/userStories/userStoriesManagementTest.java
=> Updated CorrentUoserController to LoggedUserController

src/main/java/org/springframework/dwarf/game/GameState.java, src/main/java/org/springframework/dwarf/web/LoggedUserController.java
=> Added things for GameState

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/game/ActionResolution.java, src/main/java/org/springframework/dwarf/game/ActionSelection.java, src/main/java/org/springframework/dwarf/game/Game.java, src/main/java/org/springframework/dwarf/game/MineralExtraction.java, src/main/resources/db/hsqldb/data.sql
log with test for faster game testing
=> added game with all players

TODO.txt, src/main/java/org/springframework/dwarf/game/ActionSelection.java, src/main/java/org/springframework/dwarf/game/MineralExtraction.java, src/main/webapp/WEB-INF/jsp/board/board.jsp
changed other small stuff, mineral extraction works
=> Added ToDo

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/game/ActionResolution.java, src/main/java/org/springframework/dwarf/game/ActionSelection.java, src/main/java/org/springframework/dwarf/game/Game.java, src/main/java/org/springframework/dwarf/game/MineralExtraction.java, src/main/resources/db/hsqldb/data.sql
Now they show correctly on the board.
The line grows.
=> Fixed images of database

src/main/java/org/springframework/dwarf/board/BoardCellService.java, src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/game/ActionSelection.java
@DiegoRuizGil @Pabalvcar @josgarboh @xiscomigueles
=> Phase Resolution 1/2

src/main/java/org/springframework/dwarf/board/BoardCell.java, src/main/java/org/springframework/dwarf/board/BoardController.java
=> BoardCell processing

src/main/java/org/springframework/dwarf/specialCardStrategy/RunAmok.java
Co-Authored-By: Pablo Álvarez <80222536+Pabalvcar@users.noreply.github.com>
=> RunAmok.java done

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/card/CardStrategy.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/DragonsKnockers.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/ForgesAlloy.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/GetHelp.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/OrcRaiders.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/Shide.java, src/main/java/org/springframework/dwarf/player/PlayerController.java, src/main/java/org/springframework/dwarf/player/PlayerService.java, src/main/java/org/springframework/dwarf/user/InvalidEmailException.java, src/main/java/org/springframework/dwarf/user/User.java, src/main/java/org/springframework/dwarf/user/UserController.java, src/main/java/org/springframework/dwarf/worker/IllegalPositionException.java, src/main/java/org/springframework/dwarf/worker/WorkerController.java, src/main/java/org/springframework/dwarf/worker/WorkerService.java, src/main/webapp/WEB-INF/jsp/board/board.jsp, src/main/webapp/WEB-INF/jsp/exception.jsp, src/test/java/org/springframework/dwarf/player/PlayerServiceTests.java, src/test/java/org/springframework/dwarf/worker/WorkerServiceTest.java
=> Added new Exceptions and changed xposition and yposition to select

src/main/java/org/springframework/dwarf/game/ActionResolution.java, src/main/java/org/springframework/dwarf/game/ActionSelection.java, src/main/java/org/springframework/dwarf/game/MineralExtraction.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/DragonsKnockers.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/ForgesAlloy.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/GetHelp.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/OrcRaiders.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/Seam.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/Shide.java, src/main/webapp/WEB-INF/jsp/board/board.jsp
=> Can finish action selection phase.

src/main/java/org/springframework/dwarf/game/ActionSelection.java, src/main/java/org/springframework/dwarf/game/Game.java, src/main/java/org/springframework/dwarf/game/MineralExtraction.java, src/main/java/org/springframework/dwarf/player/Player.java, src/main/java/org/springframework/dwarf/player/PlayerComparator.java, src/main/java/org/springframework/dwarf/worker/WorkerRepository.java, src/main/java/org/springframework/dwarf/worker/WorkerService.java, src/test/java/org/springframework/dwarf/worker/WorkerServiceTest.java
TheNeoStormZ has perdido la batalla.
=> Player comparator is back.

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/board/BoardService.java, src/main/webapp/WEB-INF/jsp/board/board.jsp
Now its done via buttons, solving some problems along the way.
Help with the boardcell properties: Co-Authored-By: Diego Ruiz Gil <80207565+DiegoRuizGil@users.noreply.github.com>
=> Changed way to add workers to board

src/test/java/org/springframework/dwarf/game/GameServiceTest.java, src/test/java/org/springframework/dwarf/special_card/SpecialCardServiceTest.java, src/test/java/org/springframework/dwarf/special_card/SpecialDeckServiceTest.java
Co-Authored-By: TheNeoStormZ <73660500+TheNeoStormZ@users.noreply.github.com>
=> More Test of GameService, SpecialCardService and SpecialDeckService

src/main/java/org/springframework/dwarf/worker/WorkerService.java, src/test/java/org/springframework/dwarf/forgesAlloyResources/ForgesAlloyResourcesServiceTest.java, src/test/java/org/springframework/dwarf/resources/ResourcesServiceTest.java, src/test/java/org/springframework/dwarf/worker/WorkerServiceTest.java
=> Added some tests

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/worker/Worker.java, src/main/java/org/springframework/dwarf/worker/WorkerService.java, src/main/webapp/WEB-INF/jsp/board/board.jsp
need to resolve actions, need to show card below potentially
=> Added button+post for special cards

src/main/java/org/springframework/dwarf/game/ActionResolution.java, src/main/java/org/springframework/dwarf/game/Game.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/Seam.java
Co-Authored-By: Pablo Álvarez <80222536+Pabalvcar@users.noreply.github.com>
=> updatePlayersPositions fixed

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/java/org/springframework/dwarf/game/ActionResolution.java, src/main/webapp/WEB-INF/jsp/board/board.jsp
Co-Authored-By: TheNeoStormZ <73660500+TheNeoStormZ@users.noreply.github.com>
=> Fixed player order switch

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/webapp/WEB-INF/jsp/board/board.jsp
jsp now does not crash when there arent any special actions in a deck
=> Refactored special action code, fixed jsp

src/test/java/org/springframework/dwarf/mountainCardStrategies/DragonsKnockersTests.java, src/test/java/org/springframework/dwarf/mountainCardStrategies/GetHelpTests.java, src/test/java/org/springframework/dwarf/mountainCardStrategies/OrcRaidersTests.java, src/test/java/org/springframework/dwarf/mountainCardStrategies/ShideTests.java
=> Fixed tests

src/main/java/org/springframework/dwarf/specialCardStrategies/CollapseTheShafts.java, src/test/java/org/springframework/dwarf/board/BoardControllerTests.java, src/test/java/org/springframework/dwarf/mountainCard/MountainCardControllerTests.java, src/test/java/org/springframework/dwarf/mountainCardStrategies/GetHelpTests.java, src/test/java/org/springframework/dwarf/specialCardStrategies/CollapseTheShaftsTests.java
Co-Authored-By: José Ignacio <80249164+josgarboh@users.noreply.github.com>
Co-Authored-By: TheNeoStormZ <73660500+TheNeoStormZ@users.noreply.github.com>
=> CollapseTheShaftsTest

src/main/java/org/springframework/dwarf/board/BoardCell.java, src/main/java/org/springframework/dwarf/game/MineralExtraction.java, src/test/java/org/springframework/dwarf/game/MineralExtractionTests.java, src/test/java/org/springframework/dwarf/specialCardStrategies/CollapseTheShaftsTests.java
=> Hotfix for BoardCell

src/main/java/org/springframework/dwarf/specialCardStrategies/Apprentice.java, src/test/java/org/springframework/dwarf/specialCardStrategies/AppretinceTests.java
Co-Authored-By: Pablo Álvarez <80222536+Pabalvcar@users.noreply.github.com>
=> ApprenticeTest

src/main/java/org/springframework/dwarf/game/ActionResolution.java
=> GET HELP WORKS

src/main/java/org/springframework/dwarf/game/GameService.java, src/main/java/org/springframework/dwarf/mountainCardStrategies/GetHelp.java, src/main/java/org/springframework/dwarf/worker/WorkerService.java, src/main/webapp/WEB-INF/jsp/board/board.jsp
gethelp now prevents blocks, deleteworkers now works on game finish, board view no longer shows special actions for aid workers.
=> GetHelp, deleteWorkers, board view fixed.

src/main/java/org/springframework/dwarf/board/BoardController.java, src/main/webapp/WEB-INF/jsp/errors/error403.jsp
=> Now you can spectate games

src/main/resources/db/hsqldb/data.sql
=> Now you can get badges on the first round of the test game
